### PR TITLE
[c++] Cmake bug fix and improvements

### PR DESCRIPTION
**Pull request by gspowley**
Cmake will search the system for TileDB. If not found, it will build (or download) the version specified in `libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake`.

Use this command to explicitly build using a version of TileDB installed on the system:
```
make install tiledb=<absolute-path-to-tiledb-dist>
```

Setting `LD_LIBRARY_PATH` is no longer required.

### CODE REVIEW

**Comment by Shelnutt2** [comment]
Why do we want to block system installs of TileDB by default? This is not how we handle other applications. I believe we should always support detecting system installs automatically.

**Comment by eddelbuettel** [comment]
I generally only ever install one TileDB Core version (and use `dev` for it) and generally have not had any issues with that approach.  And `make r-build` still works as it did before so no objection from me.

**Review by johnkerl — APPROVED** [review]

**Review by johnkerl — CHANGES_REQUESTED** [review]
Sorry, premature approve -- I missed Seth's very on-point feedback

**Comment by gspowley** [comment]
The latest commit reverts to searching the system for TileDB by default. 

Cmake VERSION ranges could help avoid linking to an old TileDB version, but they don't support specifying a minimum version number.

**Review by johnkerl — APPROVED** [review]

**Pull request merged**
