### PR TITLE
[python/ci] Stop wheel-smoke-test failures for MacOS > 11

### PR DESCRIPTION
**Pull request by johnkerl**
## Problem

Our current package-release CI is broken. It requires manual wheel-publish as at
https://github.com/single-cell-data/TileDB-SOMA/wiki/PyPI-packaging-notes

CI failures are like
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9189052757
following the well-intentioned but fateful #2491.

Also nightly wheel-build failures such as #2630.

## Cause

Debugging reveals:

* #2491 moved Python wheel-builds from macos 11 and 12 to 14 and 12
  * Why we did that: GitHub Actions is deprecating macos 11 runners
* Printing `python -c 'from distutils import util; print(util.get_platform())'` at build-wheel time and smoke-test-wheel time
  * Build-wheel time on macos 14: this reports (!) `macosx-10.9-universal2`
    * https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9193078472/job/25283290847#step:4:20
  * Smoke-test-wheel time on macos 14: this reports (!) `macosx-10.9-universal2`
  * https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9193078472/job/25284241544#step:4:93
* However: the wheel that's created has the substring `macosx_11` in its filename :(
  * https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9193078472/job/25283290847#step:5:1005
  * `Created wheel for tiledbsoma: filename=tiledbsoma-1.11.2.post0.dev4180921687-cp38-cp38-macosx_11_0_x86_64.whl`
* As a result, at smoke-test time, `util.get_platform()` says `macosx-10.9-universal2` and yet there is no wheel for 10.9 -- only 11.0
  * On MacOS 11, `pip install` of a wheel with either `macosx_10_9` or `macosx_11_0` in its wheel-file name succeeds
  * Not so on MacOS 14
  * So this all worked fine when the smoke-test runner was macos 11; not fine now that it's macos 12 or 14

## Attempted solutions

* :x: Setting the `CMAKE_OSX_DEPLOYMENT_TARGET: "10.9"` in our CI YAML's `env` does not help since in #2124 we set `-mmacosx-version-min=11.0` to support usage of C++17 feature `std::filesystem::path`, which overrides the env
* :x: Having our CI YAML copy files like `tiledbsoma-VERSIONHERE-cp311-cp311-macosx_11_0_arm64.whl` to `tiledbsoma-VERSIONHERE-cp311-cp311-macosx_14_0_arm64.whl` does not work, and in fact is a step in the wrong direction: since macos14 self-reports as 10.9 within `pip install` as shown above.
* :x: Having our CI YAML rename files like `tiledbsoma-VERSIONHERE-cp311-cp311-macosx_11_0_arm64.whl` to `tiledbsoma-VERSIONHERE-cp311-cp311-macosx_10_9_arm64.whl` does work, since macos 14 self-reports as 10.9 at `pip install` time.
  * ✅ Works on my laptop with macos14 and Python 3.9
  * :x: Fails in CI with macos14 and Python 3.11
  * :x: Fails in macos-on-macos Docker on my laptop with Python 3.11 (see below)

## Laptop details

With macos 14 and Python 3.9:

```
laptop$ sw_vers
ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79

laptop$ python --version
Python 3.9.13

laptop$ ll | grep macos | grep x86
-rw-r--r--@ 1 johnkerl  staff  24547997 May 21 22:50 tiledbsoma-1.11.2-cp310-cp310-macosx_11_0_x86_64.whl
-rw-r--r--@ 1 johnkerl  staff  24549656 May 21 22:50 tiledbsoma-1.11.2-cp311-cp311-macosx_11_0_x86_64.whl
-rw-r--r--@ 1 johnkerl  staff  24547829 May 21 22:50 tiledbsoma-1.11.2-cp38-cp38-macosx_11_0_x86_64.whl
-rw-r--r--@ 1 johnkerl  staff  24548029 May 21 22:50 tiledbsoma-1.11.2-cp39-cp39-macosx_11_0_x86_64.whl
-rw-r--r--@ 1 johnkerl  staff  97615624 May 21 18:53 wheels-macos-x86_64.zip

laptop$ pip install tiledbsoma-1.11.2-cp39-cp39-macosx_11_0_x86_64.whl
ERROR: tiledbsoma-1.11.2-cp39-cp39-macosx_11_0_x86_64.whl is not a supported wheel on this platform.

laptop$ cp tiledbsoma-1.11.2-cp39-cp39-macosx_11_0_x86_64.whl tiledbsoma-1.11.2-cp39-cp39-macosx_10_9_x86_64.whl

laptop$ pip install tiledbsoma-1.11.2-cp39-cp39-macosx_10_9_x86_64.whl
Processing ./tiledbsoma-1.11.2-cp39-cp39-macosx_10_9_x86_64.whl
```

Note this _exact_ logic -- successful on laptop -- fails as of
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9198109199/job/25300662543
for commit https://github.com/single-cell-data/TileDB-SOMA/pull/2620/commits/d7934164e11ec93accab0a7b084e9d1abc6e1ddf

Using https://hub.docker.com/r/sickcodes/docker-osx -- macos-on-macos Docker -- with Python 3.11 I found that the trick which worked on my laptop (macos 14 with Python 3.9), and which fails in CI here with macos 14 and Python 3.11, also fails in `sickcodes/docker-osx` with Python 3.11.

In short it seems that the renaming trick from https://stackoverflow.com/questions/65888506/error-wheel-whl-is-not-a-supported-wheel-on-this-platform works in Python 3.9 but not 3.11.

Also note:  supposedly-macos-on-macos `sickcodes/docker-osx:latest` isn't really:

```
[arch@041a7b1338f2 OSX-KVM]$ uname -a
Linux 041a7b1338f2 5.10.104-linuxkit #1 SMP Wed Mar 9 19:05:23 UTC 2022 x86_64 GNU/Linux
```

Also, why doesn't `pip install tiledbsoma` (from PyPI) fail on my Mac?

```
johnkerl@exade[prod][][~]$ pip install tiledbsoma
Collecting tiledbsoma
  Downloading tiledbsoma-1.11.1.tar.gz (291 kB)
...
Building wheels for collected packages: tiledbsoma
  Building wheel for tiledbsoma (pyproject.toml) ... |
...
```

-- it doesn't appear to be using the `.whl` file ...

Also note: on my `arm64` mac with `macos-14`:
```
$ python -c 'from distutils import util; print(util.get_platform())'
macosx-14-arm64
```

However even `macos12+arm64` runners in GHA misbehave:
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9198915278/job/25302688619
```
distutil.util.get_platform: macosx-10.9-universal2
```

# See also

* https://stackoverflow.com/questions/65888506/error-wheel-whl-is-not-a-supported-wheel-on-this-platform -- for the rename trick
* https://github.com/pypa/cibuildwheel/issues/952 -- nice to know, but this turns out not to help here
* Also note our CI YAML currently says `pypa/buildwheel@v2.11.3` whereas newer versions exist https://github.com/pypa/cibuildwheel/releases/tag/v2.18.1 👀 🤔 ... this turns out not to help here

### CODE REVIEW

**Comment by johnkerl** [comment]
Manual debug run:
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9192671442

**Comment by johnkerl** [comment]
Debugging reveals:

* #2491 moved Python wheel-builds from macos 11 and 12 to 14 and 12
  * Context: GitHub Actions is deprecating macos 11 runners
* Printing `python -c 'from distutils import util; print(util.get_platform())'` at build-wheel time and smoke-test-wheel time
  * Build-wheel time: `macosx-10.9-universal2`
    * https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9193078472/job/25283290847#step:4:20
  * Smoke-test-wheel time: `macosx-10.9-universal2`
  * https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9193078472/job/25284241544#step:4:93
* However: the wheel that's created has the substring `macosx_11` in its filename :(
  * https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9193078472/job/25283290847#step:5:1005
  * `Created wheel for tiledbsoma: filename=tiledbsoma-1.11.2.post0.dev4180921687-cp38-cp38-macosx_11_0_x86_64.whl`
* As a result, at smoke-test time, `util.get_platform()` says `macosx-10.9-universal2` and yet there is no wheel for 10.9 -- only 11.0

So I need to see how to unbreak and/or work around what CIBW is doing here.

**Comment by johnkerl** [comment]
See also:

* https://github.com/pypa/cibuildwheel/issues/952

**Comment by johnkerl** [comment]
Manual debug run:
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9193642019

**Comment by johnkerl** [comment]
Also note our CI YAML currently says `pypa/buildwheel@v2.11.3` whereas newer versions exist
https://github.com/pypa/cibuildwheel/releases/tag/v2.18.1
👀 🤔

**Comment by johnkerl** [comment]
This commit
https://github.com/single-cell-data/TileDB-SOMA/pull/2620/commits/dee4de0a05542121b1fe300b605deffb243d630b
which set the env
```
CMAKE_OSX_DEPLOYMENT_TARGET: "10.9"
```
did _not_ work --
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9193642019/job/25285197894#step:6:12
still shows wheel-file names like
```
tiledbsoma-1.11.2.post0.dev3739541002-cp310-cp310-macosx_11_0_arm64.
```

Remaining ideas:

* Have our CI _rename_ from `11_0` down to `10_9` which is a known-good after-rename step
* Have our CP _copy_ from `11_0` to `12_0`, `13_0`, and `14_0`

**Comment by johnkerl** [comment]
Manual debug run with the copy strategy from https://github.com/single-cell-data/TileDB-SOMA/pull/2620/commits/0d85de6b01eeeb42076b584735f4a497258736cc:
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9194374208

**Comment by johnkerl** [comment]
Manual debug run:
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9194821897

**Comment by johnkerl** [comment]
Manual debug run:
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9195067641/job/25290020900

**Comment by johnkerl** [comment]
Debug run with new verbosities/clarities, but, building and smoke-testing on macos 11:
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9197340871/job/25297566853

**Comment by johnkerl** [comment]
Laptop proof (macos 14 and Python 3.9):

```
laptop$ python --version
Python 3.9.13

laptop$ ll | grep macos | grep x86
-rw-r--r--@ 1 johnkerl  staff  24547997 May 21 22:50 tiledbsoma-1.11.2-cp310-cp310-macosx_11_0_x86_64.whl
-rw-r--r--@ 1 johnkerl  staff  24549656 May 21 22:50 tiledbsoma-1.11.2-cp311-cp311-macosx_11_0_x86_64.whl
-rw-r--r--@ 1 johnkerl  staff  24547829 May 21 22:50 tiledbsoma-1.11.2-cp38-cp38-macosx_11_0_x86_64.whl
-rw-r--r--@ 1 johnkerl  staff  24548029 May 21 22:50 tiledbsoma-1.11.2-cp39-cp39-macosx_11_0_x86_64.whl
-rw-r--r--@ 1 johnkerl  staff  97615624 May 21 18:53 wheels-macos-x86_64.zip

laptop$ pip install tiledbsoma-1.11.2-cp39-cp39-macosx_11_0_x86_64.whl
ERROR: tiledbsoma-1.11.2-cp39-cp39-macosx_11_0_x86_64.whl is not a supported wheel on this platform.

laptop$ cp tiledbsoma-1.11.2-cp39-cp39-macosx_11_0_x86_64.whl tiledbsoma-1.11.2-cp39-cp39-macosx_10_9_x86_64.whl

laptop$ pip install tiledbsoma-1.11.2-cp39-cp39-macosx_10_9_x86_64.whl
Processing ./tiledbsoma-1.11.2-cp39-cp39-macosx_10_9_x86_64.whl
```

**Comment by johnkerl** [comment]
Manual debug run trying `macos` with `arm64` as there are (AFAIK) runners now:
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9198915278

**Comment by johnkerl** [comment]
Experiment `pip install` -> `python -m pip install`:
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9201085806

**Comment by johnkerl** [comment]
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9198533166/job/25302055564#step:4:19 manual run
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9209822187

**Comment by johnkerl** [comment]
I ran an EC2 macos14 instance with the help of @nguyenv -- it installed the wheel without problem.

Also note:

```
>>> platform.platform()
'macOS-14.4.1-x86_64-i386-64bit'

>>> util.get_platform()
'macosx-14.0-x86_64'
```

where the first one is per @eric-hughes-tiledb and the second is what I've been using.

So this EC2 MacOS instance does not self-report as `macosx-10.9-universal2` whereas our tiledbsoma CI macos runner does.

So, useful info, but, does not allow me to interact with a failing macos system:

* CI: failing -- can't interact -- i've been pushing print-debug PRs the last day and a half
* My x86 work mac: no repro
* My personal arm64 mac: no repro
* EC2 mac x86 instance: no repro

**Comment by johnkerl** [comment]
At this point I've spent a day and a half of solid debug trying to find out why `pip install` of wheel-files doesn't work in GHA on MacOS unless MacOS v11 is being used (which GHA is deprecating).

* The smoke test -- direct `pip install` of wheel file -- works on macos11 in GHA but GHA is deprecating that
* The smoke test -- direct `pip install` of wheel file -- fails on macos > 11 GHA, with no resolution after extensive debug
* Direct `pip install` of the wheel file succeeds on both my macs (x86 and arm64) without problem
* Direct `pip install` of the wheel file succeeds on Mac EC2 instance
* `pip install tiledbsoma` works fine for recent releases

Proving that this is a CI-only issue, not worth further loss of time at this moment. I've filed #2634 to follow up.

**Comment by johnkerl** [comment]
Manual run for commit https://github.com/single-cell-data/TileDB-SOMA/pull/2620/commits/9ef7e16c96dc6e499cdcb51e7c129c2b030e1360:
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9212122517

**Review by nguyenv — APPROVED** [review]

**Comment by johnkerl** [comment]
[[sc-48079]](https://app.shortcut.com/tiledb-inc/story/48079/fix-soma-ci-smoke-test)

**Pull request merged**
