### PR TITLE
[r] Add tests for enum value filters in `SOMAExperimentAxisQuery `

### PR DESCRIPTION
**Pull request by mojaveazure**
Add a tests for doing value filters on enums in `SOMAExperimentAxisQuery`; test for levels both present and missing. Skip missing level tests for core < 2.21

addresses #1988 

[sc-43700]

### CODE REVIEW

**Review by johnkerl — APPROVED** [review]
🔥 
Thanks @mojaveazure !!

**Comment by johnkerl** [comment]
@eddelbuettel I'm happy with these as the experiment axis-query goes necessarily through dataframe

**Comment by mojaveazure** [comment]
@eddelbuettel I don't think `SOMADataFrame` has a native query interface. There are already tests for `SOMADataFrame` that work with enums (adding, updating, and handling `ordered`), and the queries in this PR all go through `obs`, which is a `SOMADataFrame`

**Comment by eddelbuettel** [comment]
I used this to test (and posted it).  The `value_filter` does what is asked for:

```r
uri <- tempfile()
pp <- data.frame(soma_joinid=as.integer64(1:344), penguins)
fromDataFrame(pp, uri, col_index=1)

set_log_level("debug")
#sdf <- SOMADataFrameOpen(uri)$read(value_filter="species == \"Adelie\"")$concat()
sdf <- SOMADataFrameOpen(uri)$read(value_filter="species == \"Frodo\"")$concat()
print(sdf)

cat("And done\n")
```

**Pull request merged**
