### PR TITLE
[r] Support `factor` and `ordered` in `SOMADataFrameCreate`

### PR DESCRIPTION
**Pull request by eddelbuettel**
**Issue and/or context:**

SOMADataFrameCreate was not aware of enumerations

**Changes:**

Support for schema creation and writing of `factor` and `ordered` has been added along with a new test.

**Notes for Reviewer:**

[SC 34370](https://app.shortcut.com/tiledb-inc/story/34370/r-support-somadataframe-factory-methods-for-enumerations)

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Dang. I got carried away. This currently the `nanoarrow` version in github not CRAN.

**Comment by eddelbuettel** [comment]
This is a fairly bening and simple PR but it is misbehaving under CI for reasons that are not entirely clear so I demoting it to 'draft'.

**Comment by eddelbuettel** [comment]
After changing a minute detail (formerly importing `tibble::as_tibble` it now passes.  So turning it back from 'draft' to the real thing.

**Review by johnkerl — APPROVED** [review]
🚢 

Looks great -- thank you! :)

**Pull request merged**
