### PR TITLE
[c++] `exists` should take in `SOMAContext`

### PR DESCRIPTION
**Pull request by nguyenv**
**Issue and/or context:** #2793, [sc-49546]

**Changes:**

Add `SOMAContext` argument for `exist` methods.

### CODE REVIEW

**Review by johnkerl — APPROVED** [review]

**Review by bkmartinjr — APPROVED** [review]
Test cases needed?

Other than that, LGTM.  TY!

**Comment by nguyenv** [comment]
Yeah I'll some C++ unit tests.

**Comment by nguyenv** [comment]
I will wait to merge this PR until @eddelbuettel and @mojaveazure confirm that it is working on the R side. There seems to be issues with `NDArray`s holding unexpected types.

**Comment by eddelbuettel** [comment]
>  There seems to be issues with NDArrays holding unexpected types.

That's a problem we see in unit tests related to `exists()` but it is orthogonal, as best as I can tell, to this extension for context.

**Pull request merged**
