### PR TITLE
[ci/python] Auto-create a GH issue on nightly CI fail

### PR DESCRIPTION
**Pull request by johnkerl**
**Issue and/or context:**

This will help to more quickly surface failures like the one fixed by #1226.

**Changes:**

Cloned shamelessly from https://github.com/TileDB-Inc/TileDB-Py.

**Notes for Reviewer:**

### CODE REVIEW

**Review by nguyenv — COMMENTED** [review]
I *think* this looks okay  but not 100% sure. You can test by forking this repo and push this commit to your forked repo's `main` branch. If you would like me to check  then let me know.

**Comment by johnkerl** [comment]
> I _think_ this looks okay but not 100% sure. You can test by forking this repo and pushing this commit to your forked repo's `main` branch. If you would like me to check then let me know.

@nguyenv yes please

I tried
https://github.com/johnkerl/TileDB-SOMA/commit/d0a95f1dcee1b0f130143fea06fd454f5138e92f 
direct to `main` on my fork, but, I am not seeing _any_ actions having run ...

**Comment by nguyenv** [comment]
OK - I will start testing this now.

**Comment by nguyenv** [comment]
OK I've finished taking a look on my forked repo. These commits look fine but please the check the `GITHUB_TOKEN` permissions for this repo. Under _Settings > Actions > General > Workflow persmissions_, the option for **Read and write permissions** should be marked. Otherwise the action will not be able to write an issue to this repo.

Another suggestion, if TileDB-SOMA does not already do this, is under _Actions persmissions_ to disable actions and resuable workflows by default and manually enter in a whitelist.

**Review by nguyenv — APPROVED** [review]

**Comment by jdblischak** [comment]
> please the check the GITHUB_TOKEN permissions for this repo. Under Settings > Actions > General > Workflow persmissions, the option for Read and write permissions should be marked. Otherwise the action will not be able to write an issue to this repo.

Sorry to intrude on this already merged PR, but I wanted to recommend an alternative approach to authentication. Setting the token globally to have read and write permissions means every single job in every workflow in this repo has write permissions for all scopes. I prefer a more granular approach. Directly in the YAML (so it's also documented), you can escalate limited permissions for a single job. In this case, only allowing the job `create_issue_on_fail` to have write permissions only to the `issues` API endpoint would look like this:

```
  create_issue_on_fail:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    needs: publish-to-pypi
```

And then you could change the default token to be read-only.

**Pull request merged**
