### PR TITLE
Use TileDB Core 2.20, TileDB-Py 0.26, TileDB-R 0.24

### PR DESCRIPTION
**Pull request by johnkerl**
[sc-41030]

### CODE REVIEW

**Comment by eddelbuettel** [comment]
This may have to be on hold until 0.24.0 is actually i) at CRAN, ii) merged into main, iii) tagged as a release, iv) built everywhere we care about (r2u, conda, ...)

We are waiting for a human override at CRAN as the package is held for an issue outside the package, and our control.

**Comment by johnkerl** [comment]
All good @eddelbuettel -- this PR is "up and ready to poke the retry button" whenever (and by whomever, although realistically I'll mostly likely be the one pushing the retry button when that's ready)

**Comment by eddelbuettel** [comment]
As just commented in another issue, it is a little different 'this time' and at least now as we have a release, binaries where we make them ... but no CRAN release (yet at least).

**Comment by johnkerl** [comment]
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/7981175554/job/21792363225?pr=2150 shows that we are getting core 2.20.1 for TileDB-SOMA-R but 2.20.0 via TileDB-Py 0.26.0:

```
Run Rscript -e 'tiledbsoma::show_package_versions()'
tiledbsoma:    1.7.99.3
tiledb-r:      0.2[4](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/7981175554/job/21792363225?pr=2150#step:11:5).0.1
tiledb core:   2.20.1
libtiledbsoma: 2.20.1
R:             R version 4.3.2 (2023-10-31)
OS:            Ubuntu 22.04.3 LTS

Run python -c 'import tiledbsoma; tiledbsoma.show_package_versions()'
tiledbsoma.__version__        1.5.0rc0.post214.dev362487835
TileDB-Py tiledb.version()    (0, 26, 0)
TileDB core version           2.20.0
libtiledbsoma version()       libtiledb=2.20.1
python version                3.10.13.final.0
OS version                    Linux 6.2.0-1019-azure
tiledbsoma.__version__    1.5.0rc0.post214.dev362487835
tiledb.version()          0.26.0
core version              2.20.0
anndata.__version__  (ad) 0.10.5.post1
numpy.__version__    (np) 1.26.4
pandas.__version__   (pd) 2.2.0
pyarrow.__version__  (pa) 15.0.0
scanpy.__version__   (sc) 1.9.8
scipy.__version__    (sp) 1.[12](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/7981175554/job/21792363225?pr=2150#step:15:13).0
python__version__         3.10.[13](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/7981175554/job/21792363225?pr=2150#step:15:14)
```

cc @ihnorton

**Comment by johnkerl** [comment]
Dependencies as discussed in Slack with @ihnorton

**Review by ihnorton — APPROVED** [review]

**Pull request merged**
