### PR TITLE
Restore pre-merge lint checks

### PR DESCRIPTION
**Pull request by ryan-williams**
**Issue and/or context:** https://github.com/single-cell-data/TileDB-SOMA/issues/2238#issuecomment-1989020356

Tracking issue: #2248

3.10 was removed from the CI matrix, but the lint/codecov conditions were not updated, inadvertently removing those checks from pre-merge CI.

### CODE REVIEW

**Comment by johnkerl** [comment]
Ohhhhhh :headdesk: ... this is my bad, thanks for catching it @ryan-williams !!

**Comment by ryan-williams** [comment]
2nd commit here fixes lint-rot that crept in last week (causing python-ci-full failures): #2236, #2047

**Comment by johnkerl** [comment]
I made #2248 to track

**Review by johnkerl — APPROVED** [review]
🔥

**Pull request merged**
