### PR TITLE
[r] Tweak coverage data generation

### PR DESCRIPTION
**Pull request by eddelbuettel**
**Issue and/or context:**

Coverage for R has been generated with default values for some of the arguments leading to generated paths missing the initial two directories `apis/r/`.  By probing a little deeper @mojaveazure and I found we could accomodate this with a combination of setting the path relative to the repository root, _and_ setting the relative path argument too.  

**Changes:**

The runner script `r-ci.sh` has been updated accordingly.

**Notes for Reviewer:**

[SC 38463](https://app.shortcut.com/tiledb-inc/story/38463/refine-coverage)

### CODE REVIEW

**Comment by eddelbuettel** [comment]
I learned once again that the 'distance between "works here" and "works at GHA"' remainst constant at 'approximately four commits'.  It now runs but gets into a (new ?) failure under coverage for which I have to add a log dumper.  Later, or maybe tomorrow.

**Review by beroy — APPROVED** [review]

**Comment by eddelbuettel** [comment]
One step forward, two steps back: it 'runs' given the path settings, but it doesn't attribute any of the tests. :sob:  So we get the correct filename, but a bunch of zeros reported.  In short, we are still fighting to adjust package `covr` to our repo layout.

**Comment by eddelbuettel** [comment]
We seem to be getting in our own way.  On may laptop (no branches, main repo of TileDB Core, R, SOMA all a few days old) I can easily do

```r
> library(covr)
> setwd("apis/r")
> Sys.setenv("CI"="TRUE")                           # to have more tests run
> res <- package_coverage(relative_path="../..")    # all defaults but inform about relative paths
> report(res)                                       # results in browser
```

Plus we can easily use the `line_exclusion=list(...)` argument to exclude `nanoarrow.*` (vendored) and `roxygen.R` (doc generation) after which we end up at 83% which isn't a bad place.

**Comment by eddelbuettel** [comment]
Some more progress.  

image

**Pull request merged**
