### PR TITLE
[r] Refactor readers for `X`, `obs`, and `var` of `SOMAExperimentAxisQuery`

### PR DESCRIPTION
**Pull request by pablo-gar**
**Issue and/or context:**

#1271

### CODE REVIEW

**Comment by pablo-gar** [comment]
Converted to draft -- testing `iterator = TRUE` for any of its uses, my current environment hangs for my >10 min when calling within or outside the `ExperimentAxisQuery`

**Comment by pablo-gar** [comment]
Behavior for hanging for a long time when `iterator=TRUE` and large SOMA objects is not an outcome of this PR, any improvement to this have to be done at the level of `SOMADataFrame$read` and `SOMASparseNDArray$read`.

**Review by eddelbuettel — COMMENTED** [review]
Looks good per se as the changes but could you add a unit test for a large enough object (or by dialing default buffer size down) showing that one (or more) of these accessors do iterate correctly?

**Comment by pablo-gar** [comment]
superseded by #1274

**Pull request closed without merging**
