### PR TITLE
[python] Update to `_create_or_open_coll` for 1.2.7 compatibility

### PR DESCRIPTION
**Pull request by johnkerl**
Testing on #1592 did not cover enough cases.

### CODE REVIEW

**Comment by johnkerl** [comment]
[sc-33078]

**Review by aaronwolen — APPROVED** [review]

**Comment by thetorpedodog** [comment]
This seems like it’s probably fine, but what is the motivation here?

**Comment by johnkerl** [comment]
@thetorpedodog chatting you on Slack

**Comment by johnkerl** [comment]
[sc-33078]

**Pull request merged**
