### PR TITLE
[python] Leverage bounding-box feature for obsm/varm outgest robustness

### PR DESCRIPTION
**Pull request by johnkerl**
## Issue and/or context

This is a follow-on to #1648 for issue #1434.

## Changes

This solves the problem on #1434, namely, occasionally `obsm` or `varm` matrices are not fully occupied, and the status quo does depend on full occupation.

For other sparse matrices we have the following:

* `X`matrices are always nobs x nvar
* `obsp` matrices are always nobs x nobs
* `varp` matrices are always nvar x nvar

but:

* `obsm` is nobs x some number -- number of PCA components, etc.
* `varm` is nvar x some number -- number of PCs, etc.
* Until #1648 we did not explicitly store the number of columns for these -- this complicates outgest

This PR provides three ways to get the number of columns for `obsm`/`varm` sparse matrices:

* Explicit user specification
* Bounding-box metadata, if present
* Try arithmetic on nnz / num_rows, for densely occupied sparse matrices -- the status quo
* Beyond that, we have to throw -- but now the error message is done with actionable advice.

## Notes for Reviewer

This PR is currently stacked on top of #1648, which it depends on. When #1648 is merged, this PR will be atop `main`.

## Additional details

Unit-test cases on this PR are thorough. The following discussion is for illustrative purposes only.

This problem was found using the Krasnow dataset which TileDB employees may find at `s3://tiledb-johnkerl/s/a/krasnow.h5ad`. (All the test-data files included in this repo before this PR have fully occupied `obsm` and `varm`. This PR introduces a test-data file with an `obsm` intentionally not fully occupied, to test this case.)

AnnData fomat:

```
>>> adata = ad.read_h5ad('krasnow.h5ad')

>>> adata.obsm["X_tSNE"].shape
(65662, 2)

>>> 65662*2
131324
```

SOMA format:

```
>>> exp = tiledbsoma.Experiment.open('krasnow')

>>> exp.ms["RNA"].obsm["X_tSNE"].nnz
131323
```

Note that this is one less than fully occupied.

Before this PR:

```
>>> tiledbsoma.io.to_anndata(exp, "RNA", var_id_name="feature_id")
Traceback (most recent call last):
...
    raise SOMAError(
tiledbsoma._exception.SOMAError: internal error: encountered non-rectangular obsm[X_tSNE]: 65662 does not divide 131323
```

After this PR, we have three options. First, if the data is old and lacks the bounding box from #1648 and henceforth, we have an improved error message:

```
>>> tiledbsoma.io.to_anndata(exp, "RNA", var_id_name="feature_id")
Traceback (most recent call last):
    raise SOMAError(
tiledbsoma._exception.SOMAError: could not determine outgest width for obsm["X_tSNE"]: please try to_anndata's obsm_varm_width_hints option
```

Second, the user can leverage this advice:

```
>>> adata = tiledbsoma.io.to_anndata(exp, "RNA", var_id_name="feature_id", obsm_varm_width_hints={"obsm":{"X_tSNE":2}})
>>> adata.obsm["X_tSNE"].shape
(65662, 2)
```

Thirdly, if the dataset is re-ingested with bounding-box support -- from this PR and henceforth -- then the following works:

```
>>> adata = tiledbsoma.io.to_anndata(exp, "RNA", var_id_name="feature_id")
>>> adata.obsm["X_tSNE"].shape
(65662, 2)
```

### CODE REVIEW

**Comment by johnkerl** [comment]
@thetorpedodog @mojaveazure @aaronwolen ping 🙏

**Comment by johnkerl** [comment]
@thetorpedodog @mojaveazure @aaronwolen ping 🙏

**Comment by johnkerl** [comment]
@thetorpedodog @mojaveazure @aaronwolen ping 🙏

**Comment by johnkerl** [comment]
@thetorpedodog @mojaveazure @aaronwolen ping 🙏

**Review by aaronwolen — APPROVED** [review]

**Comment by johnkerl** [comment]
Thanks @aaronwolen !

**Pull request merged**
