### PR TITLE
[r] Update `DESCRIPTION` to 1.5.1

### PR DESCRIPTION
**Pull request by johnkerl**
This is a small bugfix release

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Should we sweep up more PRs (and #1894 is a candidate though not a must have) and/or wait for an updated-at-CRAN SeuratObject, or is your preference to get this out ASAP?

**Comment by johnkerl** [comment]
@eddelbuettel `main` and `release-1.5` are in sync except for https://github.com/single-cell-data/TileDB-SOMA/issues/1733 which is shelved for reasons beyond our control. #1894 is still open.

The discussion last week was to tag 1.5.1 today, while @mojaveazure says he should have the Seurat issue solved later this week. (See also https://github.com/TileDB-Inc/TileDB-Cloud-JupyterHub/pull/562/commits/b01ce792788538cb3fd083d7624c1bbf9ac9ce97.)

**Comment by johnkerl** [comment]
@eddelbuettel I don't mind getting #1894 in but it  needs to be accepted and merged to `main` first.

**Review by eddelbuettel — APPROVED** [review]
:shipit:

**Comment by johnkerl** [comment]
@eddelbuettel I wasn't a reviewer on #1894 but I'll self-add, given your suggestion. Thanks!

**Comment by eddelbuettel** [comment]
I see.  Thanks for unblocking.

**Pull request merged**
