### PR TITLE
[python] Export `TileDBCreateOptions` at the top level, and add to docs

### PR DESCRIPTION
**Pull request by thetorpedodog**
Finishes the Python side of #1394.

### CODE REVIEW

**Review by johnkerl — APPROVED** [review]
Thanks @thetorpedodog !! :)

**Comment by johnkerl** [comment]
@thetorpedodog re

> Finishes the Python side of https://github.com/single-cell-data/TileDB-SOMA/issues/1394.

I believe this
https://github.com/single-cell-data/TileDB-SOMA/blob/export-create-options/apis/python/src/tiledbsoma/_dataframe.py#L133
(and likewise for the other foundational classes) still needs to be done to finish the checkbox

> Let the `create` methods in this repo take a union of `PlatformConfig` and `TileDBCreateOptions`

from #1394

**Comment by johnkerl** [comment]
Looking at #1394 and #1408 I would _think_ #1408 would have resolved that bullet, but, on #1430 (freshly rebased on top of this current now-merged PR I'm commenting on) I am still seeing from `mypy`

```
apis/python/src/tiledbsoma/_dataframe.py:355: error: Argument 2 of "write" is incompatible with supertype "DataFrame"; supertype defines the argument type as "object"  [override]
```

🤔

**Comment by thetorpedodog** [comment]
There is no runtime problem there; all that needs to happen is an update to the type annotations to reflect the changed types in somacore.

**Comment by johnkerl** [comment]
@thetorpedodog agreed it is a lint problem, not a runtime problem -- but red CI is red CI and we need to make a change.

**Comment by johnkerl** [comment]
@thetorpedodog 
https://github.com/single-cell-data/TileDB-SOMA/pull/1430/commits/87d347368bcbacc732088af0cfc9c0290378c0a3

**Pull request merged**
