### PR TITLE
[r] Upcast axis query coords to integer64

### PR DESCRIPTION
**Pull request by eddelbuettel**
**Issue and/or context:**

In #1171 @mlin points out some usabilit shortcomings with an axis query.  This PR addresses one of the two concerns and lifts the requirement for explicit `as.integer64()` casts.  Changing the naming is a litte tricker as can be confronted with one or two dimension data sets and use a list with names if case fewer than all dimensions are constrained in the query.

**Changes:**

Integer vectors are now converted to `integer64` as needed.

**Notes for Reviewer:**

#1171
[SC 27100](https://app.shortcut.com/tiledb-inc/story/27100/r-improve-usability-of-somaaxisquery-coords)

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Reverting to draft -- turns out this bites in another code path where the column in fact 32 bit int.

**Comment by eddelbuettel** [comment]
@mlin @aaronwolen @johnkerl @mojaveazure :  This is ready for review.

**Comment by eddelbuettel** [comment]
Thanks for the quick approval @johnkerl -- I may wait for @mlin to ponder it and should probably throw in a new test or two.

**Comment by johnkerl** [comment]
@eddelbuettel 💯

**Review by mlin — APPROVED** [review]
🚢

**Pull request merged**
