### PR TITLE
[Backport release-1.11] [r] Port re-indexer to the R API

### PR DESCRIPTION
**Pull request by johnkerl**
Backports #2637 to the `release-1.11` branch

### CODE REVIEW

**Comment by eddelbuettel** [comment]
This failed because GitHub has an issue accessing GitHub (!!).   As we long switched to depending on r-universe too, we might as well stick these two data packages into an r-universe build too.  Just a thought.

image

**Comment by johnkerl** [comment]
> This failed because GitHub has an issue accessing GitHub (!!). As we long switched to depending on r-universe too, we might as well stick these two data packages into an r-universe build too. Just a thought.

@eddelbuettel can you or @mojaveazure please put up a PR to help with this?

**Comment by johnkerl** [comment]
Awaiting #2649

**Comment by johnkerl** [comment]
Segfaults with and without #2649 applied. Also note #2649 segfaults without _this_ change.

**Comment by mojaveazure** [comment]
#2649 adjusts the file download timeout, it would not have done anything to handle segfaults. I've got some tests there now to try and take care of that, but as-applied here nothing would have changed

**Comment by johnkerl** [comment]
> https://github.com/single-cell-data/TileDB-SOMA/pull/2649 adjusts the file download timeout, it would not have done anything to handle segfaults. I've got some tests there now to try and take care of that, but as-applied here nothing would have changed

Agreed but I'm relucant to merge red CI -- losing our ability to find _subsequent_ problems -- "don't spread the red"

On the other hand `main` and `release-1.11` are all but identical (or will be, with this merged) and #2637 is green in `main`

And #2649 is red without this change so maybe the "red will spread" with or without this PR merged -- or #2649 ....

All very confusing :(

**Comment by johnkerl** [comment]
And @mojaveazure on the fourth hand this PR isn't super-urgent -- the indexer by itself in this `release-1.11` branch without integration with the blockwise iterator, isn't particularly useful

I did want, all else being equal, to sync `main` with `release-1.11` just _in prep_ for subsequent mods, but, if this is red today, there's no pressure to merge today

**Comment by johnkerl** [comment]
The fourth commit on this PR rebased in #2651

**Pull request merged**
