### PR TITLE
[python/ci] Unbreak wheel builds

### PR DESCRIPTION
**Pull request by johnkerl**
**Issue and/or context:** Attempt on #2337

**Changes:** per @nguyenv 

**Notes for Reviewer:**

### CODE REVIEW

**Comment by johnkerl** [comment]
Doing manual run of "sdist&wheels" from https://github.com/single-cell-data/TileDB-SOMA/actions/workflows/python-packaging.yml ... 🤞

**Comment by johnkerl** [comment]
... that failed https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8454590497/job/23160045280

**Comment by johnkerl** [comment]
Another manual run using the most recent commit:
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8455352258

**Comment by johnkerl** [comment]
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8455352258
is green

**Review by nguyenv — APPROVED** [review]

**Comment by johnkerl** [comment]
Learnings: https://github.com/single-cell-data/TileDB-SOMA/wiki/Debugging-wheel%E2%80%90build-issues

**Pull request merged**
