### PR TITLE
[c++] Match `delete[]` with `new[]`

### PR DESCRIPTION
**Pull request by johnkerl**
As discussed in Slack.

### CODE REVIEW

**Review by nguyenv — APPROVED** [review]

**Comment by johnkerl** [comment]
@nguyenv would you prefer we use `malloc` and `free` rather than `new[]` and `delete[]`?

**Comment by johnkerl** [comment]
@nguyenv hmm ... really a toss-up IMHO ... I do notice:

* There's a lot of other `new` and `delete` in that file
* No other `malloc` or `free`
* As long as C++ news memory, hands it off to C which uses it, then deletes that memory, I think all is well ...

**Comment by eddelbuettel** [comment]
The line to allocate these buffers should be this one

https://github.com/single-cell-data/TileDB-SOMA/blob/4a71f19f20c3b6ad4774942b0211df50087adb1b/libtiledbsoma/src/utils/arrow_adapter.cc#L288

so it is indeed a `new` that should be a matched by a `delete`.   Or ... as there is a `free` the allocations could a `malloc`.  But point taken that it is currently mismatched.

**Comment by johnkerl** [comment]
@eddelbuettel that is correct, lines 288 and 86 as in Slack.

**Comment by nguyenv** [comment]
I think this PR is fine as is to fix for the upcoming 2.21.0 release. Then it can be changed to malloc/free in a future PR since that's not as high priority with everything now matching correctly.

**Pull request merged**
