### PR TITLE
[c++] Fix nightly build failure on `formattable` of `json` type

### PR DESCRIPTION
**Pull request by johnkerl**
https://github.com/TileDB-Inc/tiledbsoma-feedstock/issues/153#issuecomment-2122979236

#2608

### CODE REVIEW

**Comment by jdblischak** [comment]
Testing this branch on my feedstock fork at https://github.com/jdblischak/tiledbsoma-feedstock/tree/test-nightly-formtabble-fix

**Comment by johnkerl** [comment]
> Testing this branch on my feedstock fork at https://github.com/jdblischak/tiledbsoma-feedstock/tree/test-nightly-formtabble-fix

@jdblischak did it work? (I don't see the CI, to check it myself ...)

**Comment by jdblischak** [comment]
> did it work?

Yes! The [linux-64 build with fmt10 passed](https://dev.azure.com/jdblischak/feedstock-builds/_build/results?buildId=812&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=6d4b912b-175d-51da-0fd9-4d30fe1eb4e7)

> (I don't see the CI, to check it myself ...)

Hmmm...that's surprising. I sent you the branch because I wanted you to be able to see the changes I made as well as the CI builds. Below is what I see when I access that link when logged of GitHub. I can still see the CI status icon on the commit and click it.

click

**Review by jdblischak — APPROVED** [review]
Thanks @johnkerl! 🎉

**Pull request merged**
