### PR TITLE
Update C++ CLI example

### PR DESCRIPTION
**Pull request by gspowley**
* Update the C++ CLI example to work with the new SOMA spec.
* Add more comments to C++ classes.

### CODE REVIEW

**Review by eddelbuettel — APPROVED** [review]
Lovely.  Works for me:

```r
> library(tiledbsoma)
> test_sdf("testdata/soco/pbmc3k_processed")
[2022-09-21 14:52:15.793] [tiledbsoma] [Process: 2881775] [Thread: 2881775] [info] var and obs queries are complete
[2022-09-21 14:52:15.850] [tiledbsoma] [Process: 2881775] [Thread: 2881775] [info] X/data rows = 4848644
[2022-09-21 14:52:15.850] [tiledbsoma] [Process: 2881775] [Thread: 2881775] [info]   batches = 3
> packageVersion("tiledbsoma")
[1] ‘0.0.1’
> 
```

**Comment by eddelbuettel** [comment]
This is all the accomodation I need to embed this in an R package:  an 'export this please' tag, and suppression of the `main()` routine a library cannot have.

```diff
$ colordiff ../tiledb-singlecell/libtiledbsoma/src/cli.cc src/cli.cc
36a37
> // [[Rcpp::export]]
76a78
> #if !defined(R_BUILD)
94a97
> #endif
$ 
```

**Review by johnkerl — APPROVED** [review]

**Comment by gspowley** [comment]
No problem, I'll add those tags now.

**Comment by eddelbuettel** [comment]
Perfect.  My build sets the local define to skim `main()` and that is all I need for now,  Yay!

**Pull request merged**
