### PR TITLE
[r] Use the new tiledb-r release in CI

### PR DESCRIPTION
**Pull request by eddelbuettel**
**Issue and/or context:**

We need the Enumerations-aware tiledb-r in CI.  This adds it.

**Changes:**

(Temporarily) adds two new segments for macOS and linux to r-ci.yaml

**Notes for Reviewer:**

[SC 33875](https://app.shortcut.com/tiledb-inc/story/33875/r-temporary-switch-to-rc-builds-in-ci)

#866

### CODE REVIEW

**Review by johnkerl — APPROVED** [review]
🚢 

LGTM as long as CI passes! :)

**Comment by eddelbuettel** [comment]
:crossed_fingers:

**Comment by johnkerl** [comment]
@eddelbuettel we can close this now I believe

**Comment by eddelbuettel** [comment]
@johnkerl I fear not as eg r-ci.yml goes to r-universe _because what it needs is not available elsewhere and may not be for a day_.

**Comment by johnkerl** [comment]
@eddelbuettel OK.

We can't tag 1.5.0 until all 2.17.0-rc0 dependencies are gone, but, if this PR helps soothe concerns until then, all for the good.

**Comment by johnkerl** [comment]
@eddelbuettel I did `git merge main` on this just now & there's not much left -- we are converging! :)

**Pull request merged**
