### PR TITLE
[r] Add stats API accessors

### PR DESCRIPTION
**Pull request by eddelbuettel**
#### Issue and/or context:

Issue #514 asked for stats support from the TileDB engine, this had fallen to the side because I had conflated it with requiring an interface to the query object (which it has: for subsets of the data).   

#### Changes:

This PR adds four direct interfaces to the TileDB::Stats class and compiles them directly.  We could equally well call the same functionality from the tiledb-r package but it may be preferable to minimise access to it.  

We return a JSON string and do not parse it for the user.  This could be added, but would require a whole new dependency, 

#### Notes for Reviewer:

See https://app.shortcut.com/tiledb-inc/story/25087/expose-stats-api and https://github.com/single-cell-data/TileDB-SOMA/issues/514

#### Demo

<details>

```r
> library(tiledbsoma)
> uri <- "/tmp/tiledb/penguins"    # local array used for testing
> sdf <- SOMADataFrame$new(uri)
> sdf$stats_enable()
> arr <- sdf$read()
> txt <- sdf$stats_dump()
> cat(txt, "\n")
[
  {
    "timers": {
      "Context.StorageManager.sm_load_fragment_metadata.sum": 0.000637428,
      "Context.StorageManager.sm_load_fragment_metadata.avg": 0.000637428,
      "Context.StorageManager.sm_load_array_schemas_and_fragment_metadata.sum": 0.00142219,
      "Context.StorageManager.sm_load_array_schemas_and_fragment_metadata.avg": 0.00142219,
      "Context.StorageManager.sm_load_array_schema_from_uri.sum": 0.000610096,
      "Context.StorageManager.sm_load_array_schema_from_uri.avg": 0.000610096,
      "Context.StorageManager.sm_load_all_array_schemas.sum": 0.000683514,
      "Context.StorageManager.sm_load_all_array_schemas.avg": 0.000683514,
      "Context.StorageManager.array_open_read_load_schemas_and_fragment_meta.sum": 0.00143929,
      "Context.StorageManager.array_open_read_load_schemas_and_fragment_meta.avg": 0.00143929,
      "Context.StorageManager.array_open_read_load_directory.sum": 0.00197803,
      "Context.StorageManager.array_open_read_load_directory.avg": 0.00197803,
      "Context.StorageManager.array_open_READ.sum": 0.00347599,
      "Context.StorageManager.array_open_READ.avg": 0.00347599,
      "Context.StorageManager.VFS.ArrayDirectory.list_root_uris.sum": 0.000945713,
      "Context.StorageManager.VFS.ArrayDirectory.list_root_uris.avg": 0.000945713,
      "Context.StorageManager.VFS.ArrayDirectory.list_fragment_meta_uris.sum": 0.00153488,
      "Context.StorageManager.VFS.ArrayDirectory.list_fragment_meta_uris.avg": 0.00153488,
      "Context.StorageManager.VFS.ArrayDirectory.list_commit_uris.sum": 0.00131343,
      "Context.StorageManager.VFS.ArrayDirectory.list_commit_uris.avg": 0.00131343,
      "Context.StorageManager.VFS.ArrayDirectory.list_array_schema_uris.sum": 0.00092351,
      "Context.StorageManager.VFS.ArrayDirectory.list_array_schema_uris.avg": 0.00092351,
      "Context.StorageManager.VFS.ArrayDirectory.list_array_meta_uris.sum": 0.00152712,
      "Context.StorageManager.VFS.ArrayDirectory.list_array_meta_uris.avg": 0.00152712
    },
    "counters": {
      "Context.StorageManager.read_unfiltered_byte_num": 471,
      "Context.StorageManager.read_frag_meta_size": 954,
      "Context.StorageManager.read_array_schema_size": 471,
      "Context.StorageManager.VFS.read_ops_num": 5,
      "Context.StorageManager.VFS.read_byte_num": 1229,
      "Context.StorageManager.VFS.ls_num": 5,
      "Context.StorageManager.VFS.file_size_num": 1
    }
  }
]
 
> print(str(jsonlite::fromJSON(txt)))
'data.frame':	1 obs. of  2 variables:
 $ timers  :'data.frame':	1 obs. of  24 variables:
  ..$ Context.StorageManager.sm_load_fragment_metadata.sum                     : num 0.000637
  ..$ Context.StorageManager.sm_load_fragment_metadata.avg                     : num 0.000637
  ..$ Context.StorageManager.sm_load_array_schemas_and_fragment_metadata.sum   : num 0.00142
  ..$ Context.StorageManager.sm_load_array_schemas_and_fragment_metadata.avg   : num 0.00142
  ..$ Context.StorageManager.sm_load_array_schema_from_uri.sum                 : num 0.00061
  ..$ Context.StorageManager.sm_load_array_schema_from_uri.avg                 : num 0.00061
  ..$ Context.StorageManager.sm_load_all_array_schemas.sum                     : num 0.000684
  ..$ Context.StorageManager.sm_load_all_array_schemas.avg                     : num 0.000684
  ..$ Context.StorageManager.array_open_read_load_schemas_and_fragment_meta.sum: num 0.00144
  ..$ Context.StorageManager.array_open_read_load_schemas_and_fragment_meta.avg: num 0.00144
  ..$ Context.StorageManager.array_open_read_load_directory.sum                : num 0.00198
  ..$ Context.StorageManager.array_open_read_load_directory.avg                : num 0.00198
  ..$ Context.StorageManager.array_open_READ.sum                               : num 0.00348
  ..$ Context.StorageManager.array_open_READ.avg                               : num 0.00348
  ..$ Context.StorageManager.VFS.ArrayDirectory.list_root_uris.sum             : num 0.000946
  ..$ Context.StorageManager.VFS.ArrayDirectory.list_root_uris.avg             : num 0.000946
  ..$ Context.StorageManager.VFS.ArrayDirectory.list_fragment_meta_uris.sum    : num 0.00153
  ..$ Context.StorageManager.VFS.ArrayDirectory.list_fragment_meta_uris.avg    : num 0.00153
  ..$ Context.StorageManager.VFS.ArrayDirectory.list_commit_uris.sum           : num 0.00131
  ..$ Context.StorageManager.VFS.ArrayDirectory.list_commit_uris.avg           : num 0.00131
  ..$ Context.StorageManager.VFS.ArrayDirectory.list_array_schema_uris.sum     : num 0.000924
  ..$ Context.StorageManager.VFS.ArrayDirectory.list_array_schema_uris.avg     : num 0.000924
  ..$ Context.StorageManager.VFS.ArrayDirectory.list_array_meta_uris.sum       : num 0.00153
  ..$ Context.StorageManager.VFS.ArrayDirectory.list_array_meta_uris.avg       : num 0.00153
 $ counters:'data.frame':	1 obs. of  7 variables:
  ..$ Context.StorageManager.read_unfiltered_byte_num: int 471
  ..$ Context.StorageManager.read_frag_meta_size     : int 954
  ..$ Context.StorageManager.read_array_schema_size  : int 471
  ..$ Context.StorageManager.VFS.read_ops_num        : int 5
  ..$ Context.StorageManager.VFS.read_byte_num       : int 1229
  ..$ Context.StorageManager.VFS.ls_num              : int 5
  ..$ Context.StorageManager.VFS.file_size_num       : int 1
NULL
> 
```

</details>

### CODE REVIEW

**Review by aaronwolen — CHANGES_REQUESTED** [review]
Thanks! This is great.

I was noodling this over a bit more and I don't think we need these methods attached to any of the R6 classes. Instead, what if we renamed the `.tiledb_stats_*` functions to `tiledbsoma_stats_x` (avoiding tiledb-r namespace conflicts) and just exported them directly?

**Comment by eddelbuettel** [comment]
I wondered about that too.  One potential downside may be 'interface consistency', but it is easy either.  I make them free functions and add the roxygen wrappers.

**Comment by eddelbuettel** [comment]
We have a choice of 

      tiledbsoma_stats_foo() 

versus
 
      tiledbsoma::stats_foo()

Preferred style? The former is a bit redundant inside a package namespace tiledbsoma.

**Comment by aaronwolen** [comment]
Good point—let's go with option 2.

**Comment by eddelbuettel** [comment]
Just completed round one (which is now `R CMD check --as-cran` clean, also cleaning up one leftover).  

Will rework for 'shorter names' in the tiledbsoma namespace.

**Comment by eddelbuettel** [comment]
Second revision with shorter names -- that nicer.  See e.g. the illustration provided by the unit test:

```r
    uri <- tempfile()
    create_and_populate_soma_dataframe(uri)

    sdf <- SOMADataFrame$new(uri)
    stats_enable()
    arr <- sdf$read()
    txt <- stats_dump()
    expect_true(nchar(txt) > 1000) # cannot parse JSON without a JSON package

    stats_reset()
    txt <- stats_dump()
    expect_true(nchar(txt) < 100) # almost empty JSON string
```

**Review by aaronwolen — CHANGES_REQUESTED** [review]
Thanks for the changes!

I'm all for adding `.editorconfig` but `indent_size = 4` conflicts with the R package's existing style.

**Comment by eddelbuettel** [comment]
Actually R Core may [beg to differ](https://rstudio.github.io/r-manuals/r-ints/R-coding-standards.html): 
 
> The R Core Team recommends to use a basic indentation of 4 for R and C (and most likely also Perl) code, and 2 for documentation in Rd format.

I have use the ESS snippet that follows that quote for thirty.  Consistency can have its charms.

**Review by aaronwolen — APPROVED** [review]

**Pull request merged**
