### PR TITLE
[r] Add index_column_names() (as an aliases to dimnames())

### PR DESCRIPTION
**Pull request by eddelbuettel**
**Issue and/or context:**

The spec states that `index_column_names()` shall return index (dimension) names.

**Changes:**

Aliases / wrapped existing `dimnames()` accessor

**Notes for Reviewer:**

#1006
[SC 26006](https://app.shortcut.com/tiledb-inc/story/26006/provide-index-column-name-accessor)

### CODE REVIEW

**Comment by johnkerl** [comment]
Any reason to keep dimnames? IIUC we have (by intent) zero backward-compatibility concerns until the 1.0 R release.

**Comment by eddelbuettel** [comment]
Because we use it everywhere else?

**Comment by johnkerl** [comment]
@eddelbuettel fine with me as long as it's intentional & not just a holdover for the sake of compability with earlier (also pre-release) versions of tiledbsoma

**Comment by eddelbuettel** [comment]
Intentional.  (I feared the question would come up.) But to a 20+ user of the language, `dimnames()` is very natural and idiomatic.  Yet we _of course_ want to respect the spec (hence this PR) so to me the natural is both.  "Country and Western" as per https://www.youtube.com/watch?v=vS-zEH8YmiM

**Review by johnkerl — APPROVED** [review]

**Pull request merged**
