### PR TITLE
[c++/r/python] Update to core 2.15.2, TileDB-Py 0.21.3, TileDB-R 0.19.1

### PR DESCRIPTION
**Pull request by johnkerl**
**Issue and/or context:** As these packages are now released.

**Changes:**

**Notes for Reviewer:** See also https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/17

### CODE REVIEW

**Comment by johnkerl** [comment]
In the R CI fail at
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/4821095098/jobs/8586704033?pr=1303
I do not understand

> https://github.com/single-cell-data/TileDB-SOMA/actions/runs/4821095098/jobs/8586704033?pr=1303

as I thought we had TileDB-R 0.19.1 available on CRAN
https://cran.r-project.org/web/packages/tiledb/index.html

**Comment by johnkerl** [comment]
I notice that TileDB-Py 0.21.3 has not yet arrived in Anaconda:
https://anaconda.org/tiledb/tiledb-py/labels

**Review by eddelbuettel — APPROVED** [review]
:+1:

**Comment by eddelbuettel** [comment]
> Package required and available but unsuitable version: ‘tiledb’

So sorry about that.  I had hoped an installation yesterday would be enough to have `tiledb` covered today by PPM which goes into r2u for binaries but no so such luck.  We should therefore probably add the line

```
 Rscript -e "install.packages('tiledb', repos = c('https://eddelbuettel.r-universe.dev', 'https://cloud.r-project.org'))" 
```

as a shell command in the yaml.  And maybe we even want to keep it to always test with upcoming tiledb.

**Pull request merged**
