### PR TITLE
[python] Chunked writes for DataFrame; byte-caps for Arrow-table writes

### PR DESCRIPTION
**Pull request by johnkerl**
**Issue and/or context:** Implement chunked writes for `DataFrame` in addition to `NDArray`. Along the way, offer a centralized nbytes cap for remote object stores.

**Notes for Reviewer:**

* For `SparseNDArray`, even before this PR, COO cell sizes are already capped at 24 bytes: 8 each for `soma_dim_0` and `soma_dim_1`, and 1,2,4,8 for `soma_data` depending on the cell-value type (8 bytes for `float64` and `int64`). This means that before this PR, given `goal_chunk_nnz = 100_000_000` times cell cap of 24 bytes, we already had a hard cap of 2_400_000_000 bytes per chunked write. Now we do explicit byte arithmetic, which is a logging/visibility improvement.
* For `DenseNDArray` aside from `uns`, the same is true but cell sizes are capped at 8 not 24 since we don't offer IJV triples on the data writes. That means that before this PR, we already had a hard cap of 800_000_000 bytes per chunked write. Here, too, using explicit byte arithmetic, we obtain a logging/visibility improvement.
* For `DenseNDArray` within `uns`, we were not using chunked-write logic. Now we are.
* For `DataFrame`, also we were not using chunked-write logic. Now we are.

### CODE REVIEW

**Comment by johnkerl** [comment]
Note: CI fail is Python 3.10 only, caused by SciPy 1.12, unrelated, and addressed in #2038

**Comment by johnkerl** [comment]
@ihnorton @aaronwolen ping 🙏

**Comment by aaronwolen** [comment]
Looks good to me but I'd like to have @ihnorton approve.

**Comment by johnkerl** [comment]
@ihnorton ping 🙏

**Comment by johnkerl** [comment]
@ihnorton ping 🙏

**Review by ihnorton — APPROVED** [review]

**Pull request merged**
