### PR TITLE
[r] TileDB-R 0.17.1 

### PR DESCRIPTION
**Pull request by johnkerl**
Undoes the temporary #586 as tracked by #654

### CODE REVIEW

**Review by eddelbuettel — APPROVED** [review]
Thank you!

**Review by eddelbuettel — APPROVED** [review]
Thank you!

(Approving second time as I beat you to the review request :wink: )

**Comment by eddelbuettel** [comment]
Paranoid me just wonders if any CI or other processes need binaries made?  Those sometimes take a day or two to roll in.  Source is of course current at CRAN.

**Comment by johnkerl** [comment]
> Paranoid me just wonders if any CI or other processes need binaries made? Those sometimes take a day or two to roll in. Source is of course current at CRAN.

Let's wait for CI to finish -- should suffice to answer your question, I think? 🤞

**Comment by eddelbuettel** [comment]
Sure, I obviously understand what CI does but there be other uses cases (Conda, say) we do not explicitly test and which require binaries.  Ditto at CRAN: it can be two or three days til the cross-product of {mac,win} x {r-release,r-devel} of binaries has been made.  We _should_ be fine though.  Source releases are what matter.

**Comment by johnkerl** [comment]
OK

Trying to learn here, thanks for the perspective!! :)

Please let me know if you learn of any failures I'm not aware of

**Pull request merged**
