### PR TITLE
[c++] Ensure cmake parameters are used and passed from superbuild

### PR DESCRIPTION
**Pull request by Shelnutt2**
This ensure various `TILEDB_X` settings are actually used in source builds. We also ensure that various variables for CMAKE c/c++ settings are passed from the superbuild into the subsequent dependencies and builds.

### CODE REVIEW

**Review by nguyenv — APPROVED** [review]

**Comment by johnkerl** [comment]
@nguyenv @Shelnutt2 any reason I shouldn't merge this?

**Comment by nguyenv** [comment]
The PR looks good to me.

**Comment by johnkerl** [comment]
@Shelnutt2 @nguyenv to avoid rebase issues I will merge this.

Please let me know if we need a revert and I'll be happy to do so.

**Comment by johnkerl** [comment]
Reverting, as this caused
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/4659827316

**Comment by Shelnutt2** [comment]
> Reverting, as this caused https://github.com/single-cell-data/TileDB-SOMA/actions/runs/4659827316

Can you provide more details about this PR caused the issue?

**Comment by johnkerl** [comment]
@Shelnutt2 I may have been mistaken -- the above-linked error may have been due to post-merge CI on
https://github.com/single-cell-data/TileDB-SOMA/pull/1235
👀

**Comment by johnkerl** [comment]
@Shelnutt2 I verified that it was indeed the first merge-to-main CI from _this_ PR (not #1235) that had the fail

However, I re-ran the fail and it succeeded

So this was a transient; neither PR seems to have been at fault.

**Comment by Shelnutt2** [comment]
> @Shelnutt2 I verified that it was indeed the first merge-to-main CI from _this_ PR (not #1235) that had the fail
> 
> However, I re-ran the fail and it succeeded
> 
> So this was a transient; neither PR seems to have been at fault.

Thanks for confirming!

**Pull request merged**
