### PR TITLE
[python] Wire `context` through `tiledbsoma.io.from_anndata`

### PR DESCRIPTION
**Pull request by johnkerl**
**Issue and/or context:**

Solves #1223.

**Changes:**

Wire `context` all the way from `tiledbsoma.io.from_anndata` to group/array I/O methods.

**Notes for Reviewer:**

I don't have ideas for unit-testing strategy.

What I did to test locally:

```
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_DEFAULT_REGION
```

Then edit `cfg.txt` and put in

```
vfs.s3.aws_access_key_id ***
vfs.s3.aws_secret_access_key ****
vfs.s3.region us-east-1
```

Then

```
ingestor --tiledb-config cfg.txt /path/to/local.h5ad s3://bucket/path
```

### CODE REVIEW

**Comment by johnkerl** [comment]
Sorry @atolopko-czi @thetorpedodog , I put up this PR too soon -- need to fix CI

**Comment by johnkerl** [comment]
Sorry @atolopko-czi @thetorpedodog -- I put up this PR too soon. Need to fix CI.

**Comment by johnkerl** [comment]
@thetorpedodog @atolopko-czi @mlin ready for review

**Review by thetorpedodog — APPROVED** [review]
This looks good for what it is. In the grand scheme of things this shouldn’t be necessary, because we shouldn’t have to manually pass around context because we can use the built-in <code>add_new_<i>whatever</i></code> functions and regular `index[access]` rather than the weird stuff we’re doing here, but that’s a matter for https://github.com/single-cell-data/TileDB-SOMA/issues/895.

**Pull request merged**
