### PR TITLE
[r] Bump `apis/r/DESCRIPTION` for `main` past current latest release

### PR DESCRIPTION
**Pull request by johnkerl**
* https://github.com/single-cell-data/TileDB-SOMA/releases/tag/1.6.1 exists
* `main` should be "past" that

### CODE REVIEW

**Review by eddelbuettel — COMMENTED** [review]
Maybe 1.6.9, or 1.6.99, 1.6.9000 is better as we may well have releases 1.6.2, 1.6.3, ... and so on which would once again jump ahead of the number here.

If we pick a higher 'delta' we'd be safe from that confusion that 'newer sorts lower' which is not desirable.

**Review by aaronwolen — APPROVED** [review]

**Comment by johnkerl** [comment]
Sorry, I changed from 1.6.1.1 to 1.6.99 on @eddelbuettel ' s advice but then realized @aaronwolen had accepted before my mod -- re-requesting review ...

**Comment by johnkerl** [comment]
In Slack, Aaron propopsed 1.6.1.1.

@aaronwolen @eddelbuettel @mojaveazure I am serving in a clerical role here. Please offer a 2/3 majority opinion and I'll commit it.

**Comment by mojaveazure** [comment]
My 2¢: if a theoretical 1.6.2 would pull from `main`, I vote for 1.6.1.1; otherwise, 1.6.99 or whatever

**Comment by johnkerl** [comment]
@mojaveazure per our [established procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases) a hypothetical 1.6.2 would be on the `release-1.6` branch, not on `main`.

**Comment by aaronwolen** [comment]
Agreed, 1.6.1.1 aligns with the convention we've been using to be consistent with tiledb-r.

**Review by mojaveazure — APPROVED** [review]

**Comment by johnkerl** [comment]
* @eddelbuettel is OK with 1.6.99, and less OK with 1.6.1.1
* @mojaveazure prefers 1.6.99 if a 1.6.2 would be tagged from `release-1.6` rather than `main`, which is in fact the case
* @aaronwolen prefers 1.6.1.1
* As above, I am not an R expert
* 2 of 3 go with 1.6.99

**Comment by johnkerl** [comment]
Our [established procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases) has been updated to reflect this decision:

https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases/_compare/a4d2ebf66de4128d8f2987290e8c0e3789098701...747bbebab373dbfeceff35ea03d66e8cb455c3b2

**Pull request merged**
