### PR TITLE
[python] Update coordinate space <-> JSON converters

### PR DESCRIPTION
**Pull request by nguyenv**
* Update `transform_from_json` and `transform_to_json` to support additional `CoordinateSpace` types `UniformScaleTransform` and `ScaleTransform`
* Correct error message in `PointCloud.coordinate_space` setter

### CODE REVIEW

**Review by jp-dark — APPROVED** [review]
Thanks! We'll need to add these changes to the `main` branch now too.

**Comment by nguyenv** [comment]
> Thanks! We'll need to add these changes to the main branch now too.

Does that mean I should merge this into `main` instead of `spatial`?

**Comment by nguyenv** [comment]
These changes are needed for #3110. I have these commits merged into that branch too.

**Comment by jp-dark** [comment]
> > Thanks! We'll need to add these changes to the main branch now too.
> 
> Does that mean I should merge this into `main` instead of `spatial`?

It should be merged into both.

**Pull request merged**
