### PR TITLE
[r] No more "Last 13 lines of output:" in CI

### PR DESCRIPTION
**Pull request by johnkerl**
As discussed in Slack

### CODE REVIEW

**Review by bkmartinjr — APPROVED** [review]

**Comment by eddelbuettel** [comment]
Likely redundant because of https://github.com/single-cell-data/TileDB-SOMA/blob/main/apis/r/tools/r-ci.sh#L42

**Review by mojaveazure — APPROVED** [review]

**Comment by johnkerl** [comment]
I am seeing output I didn't see before. This is a good thing.

**Comment by eddelbuettel** [comment]
What's the test command?  Are you going through `r-ci.sh` which should have the value, or via `R CMD ...` directly?

**Comment by johnkerl** [comment]
@eddelbuettel I am seeing more output before in CI logs linked to from these PRs here in GitHub. I am happy with that fact.

**Comment by eddelbuettel** [comment]
@johnkerl I am happy you are happy but you did not answer my question to which my curious mind would still love an answer:  how did you trigger the tests so that setting YML fixed?

(Longer story R also reflects env variables just for checking from a file `~/.R/check.Renviron`, if it exists, so I have been contemplating having the `bootstrap` step during `r-ci.sh` run create it.  For that more info hence my question.)

**Comment by johnkerl** [comment]
@eddelbuettel I don't know the answer to your question.

* Before this PR I was seeing "Last 13 lines of output" when clicking through "Checks" links on PRs in this repo
* After this PR I am seeing more output
* That is all I know, and all I need to know

**Comment by eddelbuettel** [comment]
@johnkerl So you are saying that the test was triggered as before by `cd apis/r && tools/r-ci.sh run_tests`. I asked you because during the ongoing discussions around the CI fail we had brought the topic of triggering the tests differently (e.g. via a call to `R CMD check ...`.    So what this shows then is that `r-ci.sh` was supposed to already supply the setting but didn't.  This gives me more to work with so thanks for all your continued help in finding this.

**Pull request merged**
