### PR TITLE
[python/ci] Complete 3.8 -> 3.11 work

### PR DESCRIPTION
**Pull request by johnkerl**
As surfaced in the nightly smoke test for wheel-install:
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8294234646/job/22699837592

Follow-on/completion from #2267

### CODE REVIEW

**Review by nguyenv — APPROVED** [review]

**Comment by johnkerl** [comment]
Note for posterity: this was surfaced in a nightly smoke test. To run it sooner I went to the Actions page for this repo, selected the "TileDBSOMA python sdist & wheels CI", and "Run workflow" and the branch name for this PR.

Screenshot 2024-03-15 at 9 34 03 AM

Screenshot 2024-03-15 at 9 34 15 AM

**Review by jp-dark — APPROVED** [review]

**Review by jdblischak — APPROVED** [review]

**Comment by johnkerl** [comment]
Smoke-test fail after manual run
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8297065902/job/22708767588
👀

**Comment by jdblischak** [comment]
Looks like more mixing of py38 and py311

```sh
Setting up libpython3.8-dev:amd64 (3.8.10-0ubuntu1~20.04.9) ...
Setting up python3-pip (20.0.2-5ubuntu1.10) ...
Setting up g++-9 (9.4.0-1ubuntu1~20.04.2) ...
Setting up python3.8-dev (3.8.10-0ubuntu1~20.04.9) ...

# skipping a few lines

ERROR: tiledbsoma-1.5.0rc0.post244.dev566639412-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl is not a supported wheel on this platform.

```

**Comment by johnkerl** [comment]
Confirmed:
https://github.com/single-cell-data/TileDB-SOMA/blob/kerl/smoke-test-more/.github/workflows/python-packaging.yml#L147-L156

```
ubuntu@anzo[prod][][~]$ alias dreb
alias dreb='docker run --rm -it --entrypoint=/bin/bash'

ubuntu@anzo[prod][][~]$ dreb ubuntu:20.04

root@0b6965a860e0:/# apt-get -qq update

root@0b6965a860e0:/# apt-get install -y python3-pip python3-wheel
...

root@0b6965a860e0:/# python3 --version
Python 3.8.10
```

**Comment by johnkerl** [comment]
Manual run https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8297954893 successful

**Pull request merged**
