### PR TITLE
[python] Drop unused categories in `ExperimentAxisQuery.to_anndata`

### PR DESCRIPTION
**Pull request by nguyenv**
**Issue and/or context:**

#2765

**Changes:**

- Create `ExperimentAxisQuery` which inherits from somacore's `query.ExperimentAxisQuery`
- `ExperimentAxisQuery.to_anndata` iterates through each column and drops unused categories

**Notes for Reviewer:**

Should this be implemented in somacore instead?

### CODE REVIEW

**Review by johnkerl — CHANGES_REQUESTED** [review]
This is awesome!

I see no reason not to do this in somacore ...

**Comment by ivirshup** [comment]
fwiw, anndata will move to not doing this by default. This new behavior will be available as a feature flag in anndata 0.11.0.

**Comment by ivirshup** [comment]
One of the reasons we are doing this is so that we can maintain consistent categorical labels across objects. Which would be particularly useful for objects extracted from a large corpus like census.

**Comment by johnkerl** [comment]
@nguyenv sorry for the delay, I was AFK for a bit.

To quicken things, I pushed this commit just now to this PR:
https://github.com/single-cell-data/TileDB-SOMA/pull/2811/commits/f1ba80057954eb2f4be5225541e93857bf43530f

**Comment by johnkerl** [comment]
@nguyenv I'll let you revert the changes to `_experiment.py` (now that they're in `somacore`), and, parameterize `drop_levels` in your unit-test cases

**Comment by nguyenv** [comment]
Yes will do that now.

**Review by johnkerl — APPROVED** [review]
🚢

**Pull request merged**
