### PR TITLE
[python] Support `Enumeration` in Python API

### PR DESCRIPTION
**Pull request by nguyenv**
**Issue and/or context:** #866

**Changes:**

Reads are done in C++. Writes are done through TileDB-Py (https://github.com/TileDB-Inc/TileDB-Py/pull/1790).

**Notes for Reviewer:**

Depends on https://github.com/single-cell-data/TileDB-SOMA/pull/1519.

### CODE REVIEW

**Comment by johnkerl** [comment]
[sc-30316]

**Comment by nguyenv** [comment]
This PR is now at a point where it can be evaluated for feedback.

**Comment by johnkerl** [comment]
@nguyenv those are tests I created -- I'll help take a look

**Review by johnkerl — APPROVED** [review]

**Comment by johnkerl** [comment]
This has the same interop fail as #1519 which I am debugging. Otherwise looks good.

**Pull request merged**
