### PR TITLE
[r] Update `write_soma.data.frame()` to support categoricals

### PR DESCRIPTION
**Pull request by mojaveazure**
Allow `write_soma.data.frame()` to write factors as categoricals. `write_soma()` will no longer cast factors to characters prior to writing
Redo of #1683 since it got removed from #1559

### CODE REVIEW

**Review by eddelbuettel — APPROVED** [review]
Should we add a simple test for round-turn?

**Review by aaronwolen — APPROVED** [review]
Thank you! I'll second Dirk's request for a unit test but otherwise looks good to go.

**Review by johnkerl — APPROVED** [review]

**Review by johnkerl — CHANGES_REQUESTED** [review]
Let's get the unit-test case in

**Review by johnkerl — APPROVED** [review]
🚢 
Thanks @mojaveazure !!

**Pull request merged**
