### PR TITLE
[r] Set the package version to 1.5.0, and update `NEWS.md`

### PR DESCRIPTION
**Pull request by eddelbuettel**
**Issue and/or context:**

Following on #1854 / #1855 the PR sets to package version to 1.5.0

**Changes:**

None

**Notes for Reviewer:**

[SC 36501](https://app.shortcut.com/tiledb-inc/story/36501/roll-version-to-1-5-0)

### CODE REVIEW

**Review by johnkerl — APPROVED** [review]

**Review by aaronwolen — CHANGES_REQUESTED** [review]
Can you update the header in NEWS.md as well?

**Comment by eddelbuettel** [comment]
> Can you update the header in NEWS.md as well?

Sure thing. Thanks for catching that. Someone with a bit of time and good cup (or pot !!) of coffee or tea may want to expand NEWS.md for all the changes since 1.4.0.

**Comment by aaronwolen** [comment]
Good call! Would you be up for adding some details about the enumeration support in this pr?

**Comment by johnkerl** [comment]
@aaronwolen @eddelbuettel https://github.com/single-cell-data/TileDB-SOMA/pull/1856/commits/7435fc09d4bf707acb3446c006ef23e719056a8f with `NEWS.md` changes

**Review by johnkerl — APPROVED** [review]

**Review by aaronwolen — APPROVED** [review]

**Pull request merged**
