### PR TITLE
[python] Fix `failed to convert buffer` on `update_obs`/`update_var`

### PR DESCRIPTION
**Pull request by johnkerl**
**Issue and/or context:** #2517 / [sc-46654]

**Changes:** As described in the PR

**Notes for Reviewer:**

### CODE REVIEW

**Comment by johnkerl** [comment]
Moving back to draft status until I add a unit-test case

**Comment by johnkerl** [comment]
@nguyenv @ryan-williams ready for review 🙏

**Review by ryan-williams — APPROVED** [review]

**Comment by johnkerl** [comment]
@nguyenv thoughts?

**Review by nguyenv — APPROVED** [review]
Looks good to me. I know this already existed prior to this PR, but I was just wondering it was necessary for `nullable_fields` to be a `set` since it would be more efficient to append to a list than add to an (immutable) set. But I don't think this is something that needs to be changed.

**Pull request merged**
