### PR TITLE
[r] Fix quoting for a particular Docker-build environment (`main`)

### PR DESCRIPTION
**Pull request by johnkerl**
Sibling of #2102 on `main`

### CODE REVIEW

**Comment by eddelbuettel** [comment]
I had my battles over the years with similar things between shell script (snippets), `configure`, and various (CRAN particularly) build systems ... but I also have the gnarling suspicion that _maybe_ we (also ?) need to protect it where these variables are _used_ rather than where they are defined.

I recall you showed an error where the `-std=` broke off.  Was that a `make` call?

**Comment by johnkerl** [comment]
@eddelbuettel I have a failed Docker build without this fix, and succeeded with it

Quoting at the use-spot would result in things like `"g++ -arch x86_64 -std=gnu++17"` being a single argv0 which, in this particular case, is not desired.

**Review by eddelbuettel — APPROVED** [review]
:shipit: to robustify against annoying `/bin/sh` implementations

**Comment by johnkerl** [comment]
Thank you @eddelbuettel !

**Comment by johnkerl** [comment]
Re the above backport-fail: by one means or another (it doesn't matter which, and it isn't work even taking the time to search through commit history) the `release-1.7` branch already has this fix.

**Pull request merged**
